# Generated by Django 5.2.1 on 2025-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
