# Generated by Django 5.2.6 on 2025-09-10 17:01

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_price_product_base_price_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[products.validators.pricing_rule]),
        ),
    ]
