# Generated by Django 5.2.6 on 2025-09-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to='products/main_images/'),
        ),
    ]
