# Generated by Django 5.2.6 on 2025-09-11 07:06

import django.db.models.deletion
import products.utils
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to=products.utils.product_main_image_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.utils.product_variant_image_path, validators=[products.validators.validate_image]),
        ),
        migrations.CreateModel(
            name='ProductMediaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('IMAGE_ROW', 'Image Row (3-up)'), ('VIDEO', 'Video Block'), ('COLLAGE', 'Collage Grid'), ('FULL_IMAGE', 'Full-width Image')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_sections', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductMediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('TEXT', 'Text')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/media/', validators=[products.validators.validate_image])),
                ('video_url', models.URLField(blank=True, help_text='External video link', null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.productmediasection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
