# Generated by Django 5.2.6 on 2025-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_main_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmediaitem',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
