# Generated by Django 5.2.6 on 2025-09-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
