# Generated by Django 5.2.1 on 2025-09-22 13:52

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Main product price', max_digits=10, null=True, validators=[products.validators.pricing_rule]),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Total stock across all variants'),
        ),
    ]
