# Generated by Django 5.2.1 on 2025-09-19 14:17

import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='business_document',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='legal_name',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='logo',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='account_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('HBL', 'Habib Bank Limited'), ('MCB', 'Muslim Commercial Bank'), ('UBL', 'United Bank Limited')], null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/shop_logo/', validators=[users.validators.validate_image_size]),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tax_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=255),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(blank=True, choices=[('admin', 'Admin'), ('super_admin', 'SuperAdmin')], default='admin', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_payment_method', models.CharField(blank=True, choices=[('cash_on_delivery', 'CashOnDelivery'), ('stripe', 'Stripe'), ('paypal', 'Paypal'), ('amazonpay', 'AmazonPay')], default='cash_on_delivery', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('sales', 'Sales'), ('support', 'Support'), ('operations', 'Operations')], default='sales', max_length=255, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('permissions_level', models.CharField(blank=True, choices=[('basic', 'BASIC'), ('senior_manager', 'SeniorManager')], default='basic', max_length=255, null=True)),
                ('assigned_vendors', models.ManyToManyField(blank=True, related_name='assigned_vendors', to='users.vendorprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
