# Generated by Django 5.2.6 on 2025-09-25 10:55

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_update_username_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pictures/', validators=[users.validators.validate_image_size]),
        ),
    ]
