# Generated by Django 5.2.6 on 2025-09-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_permission_role_permissionrole_roleuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionrole',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='permissionrole',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='permissionrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='PermissionRole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RoleUser',
        ),
    ]
